name: CI/CD Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch if needed)
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image (arm64 only)
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/better-demo:latest

      - name: Copy SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts (optional)
        if: env.SSH_KNOWN_HOSTS != ''
        run: |
          echo "${SSH_KNOWN_HOSTS}" > ~/.ssh/known_hosts
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Deploy to remote server via SSH
        env:
          IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/better-demo:latest
          DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
        run: |
          ssh -o StrictHostKeyChecking=no -p 5022 ${DEPLOY_USER}@${DEPLOY_SERVER} \
            'bash -s' < deploy/remote-deploy.sh $IMAGE
